CREATE TABLE TB_CLIENTES
(
	CPF VARCHAR2(11),
	NOME VARCHAR2(100),
	ENDERECO1 VARCHAR2(150),
	ENDERECO2 VARCHAR2(150),
	BAIRRO VARCHAR2(50),
	CIDADE VARCHAR2(50),
	ESTADO VARCHAR2(2),
	CEP VARCHAR2(8),
	DATA_NASCIMENTO DATE,
	IDADE INTEGER,
	SEXO VARCHAR2(1),
	LIMITE_CREDITO NUMBER(15,2),
	VOLUME_COMPRA NUMBER,
	PRIMEIRA_COMPRA NUMBER(1)
)

CREATE TABLE TB_VENDEDORES
(
	MATRICULA VARCHAR2(5),
	NOME VARCHAR2(100),
	DATA_ADMISSAO DATE,
	PERCENTUAL_COMISSAO NUMBER
)

INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES ('1040107', 'Light', 'Lata', '350 ml', 'Melancia', 4.56);

INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES ('1037797', 'Clean', 'PET', '2 Litros', 'Laranja', 16.01)

INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES ('1000889', 'Sabor da Montanha', 'Garrafa', '700 ml', 'Uva', 6.31)

INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES ('1004327', 'Videira do Campo', 'PET', '1,5 Litros', 'Melancia', 19.51)

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00233', 'Joao Geraldo da Fonseca', '01/12/2015', 0.10)

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00400', 'Maria Do Rosario', '23/07/2012', 0.15)

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00810', 'Marcia Almeida', '14/12/2016', 0.18)

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00414', 'Carlos Moreira', '13/11/2015', 0.14)

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00934', 'Juvenildo Martins', '09/03/2010', 0.20)

SELECT * FROM TB_VENDEDORES

SELECT * FROM TB_PRODUTOS 

SELECT * FROM TB_CLIENTES 

UPDATE TB_PRODUTOS SET TAMANHO = '350 ml', EMBALAGEM = 'Lata', PRECO_LISTA = 5.50
WHERE PRODUTO = '1037797'

UPDATE TB_VENDEDORES SET PERCENTUAL_COMISSAO = 0.1 WHERE MATRICULA = '00810'

DELETE FROM TB_PRODUTOS WHERE PRODUTO = '1037797'

DELETE FROM TB_VENDEDORES WHERE MATRICULA = '00400'

ALTER TABLE TB_PRODUTOS ADD CONSTRAINT PK_TB_PRODUTOS PRIMARY KEY(PRODUTO)

ALTER TABLE TB_VENDEDORES ADD CONSTRAINT PK_TB_VENDEDORES PRIMARY KEY(MATRICULA)

ALTER TABLE TB_CLIENTES ADD CONSTRAINT PK_TB_CLIENTES PRIMARY KEY(CPF)

INSERT INTO TB_CLIENTES (CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO , CEP, DATA_NASCIMENTO,
IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA)
VALUES ('00333434577', 'João da Silva', 'Rua Projetada Numero 10', NULL, 'Vila Roman', 'Tres rios', 'RJ',
'12980000', '12/10/1965', 56, 'M', 100000, 2000, 0)

SELECT TO_CHAR(DATA_NASCIMENTO, 'MM') FROM TB_CLIENTES

DELETE FROM TB_CLIENTES WHERE CPF = '00333434577'

/* INSERIR COM DATA NO FORMATO DESEJADO */
INSERT INTO TB_CLIENTES (CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO , CEP, DATA_NASCIMENTO,
IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA)
VALUES ('00333434577', 'João da Silva', 'Rua Projetada Numero 10', NULL, 'Vila Roman', 'Tres rios', 'RJ',
'12980000', TO_DATE('12/10/1965', 'DD/MM/YYYY'), 56, 'M', 100000, 2000, 0)

BEGIN
	INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
	VALUES('00265', 'Jonh Wayne', TO_DATE('03/27/2019', 'MM/DD/YYYY'), 0.12);
	
	INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
	VALUES('00777', 'Katy Peterson', TO_DATE('02/04/2020', 'MM/DD/YYYY'), 0.10);
	
	INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
	VALUES('00342', 'Rodrigo Almeida', TO_DATE('18/01/2022', 'DD/MM/YYYY'), 0.09);
	
	INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
	VALUES('00729', 'Patricia Martins', TO_DATE('02/01/2022', 'DD/MM/YYYY'), 0.09);
END;