DECLARE
	v_ID SEGMERCADO.ID%TYPE := 2; 
	v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
BEGIN
	SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = v_ID; /* Com o INTO nos colocamos o resultado da consulta na variavel v_DESCRICAO */
END;

/* FUNCAO */
/* ESTRUTURA DA FUNCAO */
CREATE OR REPLACE FUNCTION 

RETURN 

IS 

BEGIN
	
END;


/* EXERCICIO */
CREATE OR REPLACE FUNCTION obter_descricao_segmercado
(p_ID IN SEGMERCADO.ID%TYPE)
RETURN SEGMERCADO.DESCRICAO%TYPE /* vai retorna o tipo do campo descricao */
IS 
	v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
BEGIN
	SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = p_ID;
	RETURN v_DESCRICAO;
END;

SELECT obter_descricao_segmercado(id) FROM SEGMERCADO WHERE ID = 1;



SELECT pe.DESCRICAO, RETORNA_CATEGORIA(COD) FROM PRODUTO_EXERCICIO pe 

CREATE OR REPLACE FUNCTION RETORNA_CATEGORIA 
(p_COD IN PRODUTO_EXERCICIO.COD%TYPE)
RETURN PRODUTO_EXERCICIO.CATEGORIA%TYPE
IS 
	v_CATEGORIA PRODUTO_EXERCICIO.CATEGORIA%TYPE;
BEGIN 
	SELECT CATEGORIA INTO v_CATEGORIA FROM PRODUTO_EXERCICIO WHERE COD = p_COD;
	RETURN v_CATEGORIA;
END;


/* PROCEDURE */
SELECT * FROM CLIENTE;
SELECT * FROM SEGMERCADO;

CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE
(p_ID CLIENTE.ID%TYPE,
p_RAZAO_SOCIAL CLIENTE.RAZAO_SOCIAL%TYPE,
p_CNPJ CLIENTE.CNPJ%TYPE,
p_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE,
p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE,
p_CATEGORIA CLIENTE.CATEGORIA%TYPE)
IS 
BEGIN 
	INSERT INTO CLIENTE(ID, RAZAO_SOCIAL, CNPJ, SEGMERCADO_ID, DATA_INCLUSAO, FATURAMENTO_PREVISTO, CATEGORIA) 
	VALUES(p_ID, p_RAZAO_SOCIAL, p_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, p_CATEGORIA);
	COMMIT;
END;

BEGIN
	INCLUIR_CLIENTE(1, 'SUPERMERCADOS X', '1234567890', 1, 90000, 'MEDIO GRANDE');
END;


/* EXERCICIO PROCEDURE DE INCLUIR */
SELECT * FROM PRODUTO_VENDA_EXERCICIO;
SELECT * FROM PRODUTO_EXERCICIO;

CREATE OR REPLACE PROCEDURE INCLUINDO_DADOS_VENDA
(p_ID PRODUTO_VENDA_EXERCICIO.ID%TYPE,
p_COD_PRODUTO PRODUTO_VENDA_EXERCICIO.COD_PRODUTO%TYPE,
p_DATA PRODUTO_VENDA_EXERCICIO."DATA"%TYPE,
p_QUANTIDADE PRODUTO_VENDA_EXERCICIO.QUANTIDADE%TYPE,
p_PRECO PRODUTO_VENDA_EXERCICIO.PRECO%TYPE,
p_VALOR_TOTAL PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE,
p_PERCENTUAL_IMPOSTO PRODUTO_VENDA_EXERCICIO.PERCENTUAL_IMPOSTO%TYPE)
IS 
BEGIN 
	INSERT INTO PRODUTO_VENDA_EXERCICIO(ID, COD_PRODUTO, "DATA", QUANTIDADE, PRECO, VALOR_TOTAL, PERCENTUAL_IMPOSTO) 
	VALUES(p_ID, p_COD_PRODUTO, p_DATA, p_QUANTIDADE, p_PRECO, p_VALOR_TOTAL, p_PERCENTUAL_IMPOSTO);
	COMMIT;
END;

BEGIN
	INCLUINDO_DADOS_VENDA(1, '41232', TO_DATE('1/1/2022', 'DD/MM/YYYY'), 100, 10, 1000, 10);
END;


DECLARE
    v_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type := 65000;
    v_CATEGORIA CLIENTE.CATEGORIA%type;
BEGIN
    IF v_FATURAMENTO <= 10000 THEN
        v_CATEGORIA := 'PEQUENO';
    ELSIF v_FATURAMENTO <= 50000 THEN
        v_CATEGORIA := 'MÉDIO';
    ELSIF v_FATURAMENTO <= 100000 THEN
        v_CATEGORIA := 'MÉDIO GRANDE';
    ELSE
        v_CATEGORIA := 'GRANDE';
    END IF;
END;


CREATE OR REPLACE FUNCTION CATEGORIA_CLIENTE
(p_FATURAMENTO IN CLIENTE.FATURAMENTO_PREVISTO%TYPE)
RETURN CLIENTE.CATEGORIA%TYPE
IS 
	v_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN 
	IF p_FATURAMENTO <= 10000 THEN
        v_CATEGORIA := 'PEQUENO';
    ELSIF p_FATURAMENTO <= 50000 THEN
        v_CATEGORIA := 'MÉDIO';
    ELSIF p_FATURAMENTO <= 100000 THEN
        v_CATEGORIA := 'MÉDIO GRANDE';
    ELSE
        v_CATEGORIA := 'GRANDE';
    END IF;
	RETURN v_CATEGORIA;
END;


SELECT c.CNPJ, c.FATURAMENTO_PREVISTO, CATEGORIA_CLIENTE(c.FATURAMENTO_PREVISTO) 
FROM CLIENTE c 
GROUP BY c.CNPJ, c.FATURAMENTO_PREVISTO, CATEGORIA_CLIENTE(c.FATURAMENTO_PREVISTO);


SELECT pve.* FROM PRODUTO_VENDA_EXERCICIO pve;

SELECT pe.DESCRICAO, pe.CATEGORIA, RETORNA_IMPOSTO(pe.COD) AS IMPOSTO
FROM PRODUTO_EXERCICIO pe 
GROUP BY pe.DESCRICAO, pe.CATEGORIA, RETORNA_IMPOSTO(pe.COD);

CREATE OR REPLACE FUNCTION RETORNA_IMPOSTO 
	(p_COD IN PRODUTO_EXERCICIO.COD%TYPE)
RETURN PRODUTO_VENDA_EXERCICIO.PERCENTUAL_IMPOSTO%TYPE
IS 
	v_CATEGORIA PRODUTO_EXERCICIO.CATEGORIA%TYPE;
	v_IMPOSTO PRODUTO_VENDA_EXERCICIO.PERCENTUAL_IMPOSTO%TYPE;
BEGIN
	v_CATEGORIA := RETORNA_CATEGORIA(p_COD);
	IF TRIM(v_CATEGORIA) = 'Sucos de Frutas' THEN
        v_IMPOSTO := 10;
    ELSIF  TRIM(v_CATEGORIA) = 'Águas' THEN
        v_IMPOSTO := 20;
    ELSIF  TRIM(v_CATEGORIA) = 'Mate' THEN
        v_IMPOSTO := 15;
    END IF;
    RETURN v_IMPOSTO;
END;































