/* Procedure é um bloco de codigo PLSQL que executa operações e pode ser chamado repetidamente */
/* Equivalente a um método(função) */

/* estrutura da procedure */
CREATE 

IS

BEGIN
	
END;

/* CRIACAO DA PROCEDURE */
CREATE PROCEDURE incluir_segmercado
(p_ID IN NUMBER,								/* entre CREATE PROCEDURE e IS declara os parametros de entrada*/
p_DESCRICAO IN VARCHAR2)
IS										        /* entre IS e BEGIN declara as variaveis*/
BEGIN
	INSERT INTO SEGMERCADO(ID, DESCRICAO) VALUES (p_ID, UPPER(p_DESCRICAO));
	COMMIT;
END;

SELECT * FROM SEGMERCADO;

/* USAR PROCEDURE */
BEGIN
	incluir_segmercado(4, 'Farmaceuticos');
END;

/* ALTERAR PROCEDURE */
CREATE OR REPLACE PROCEDURE incluir_segmercado
(p_ID IN SEGMERCADO.ID%TYPE,								/* entre CREATE PROCEDURE e IS declara os parametros de entrada*/
p_DESCRICAO IN SEGMERCADO.DESCRICAO%TYPE)
IS										        /* entre IS e BEGIN declara as variaveis*/
BEGIN
	INSERT INTO SEGMERCADO(ID, DESCRICAO) VALUES (p_ID, UPPER(p_DESCRICAO));
	COMMIT;
END;

CREATE OR REPLACE PROCEDURE incluir_segmercado2
(p_ID IN SEGMERCADO.ID%TYPE,								/* entre CREATE PROCEDURE e IS declara os parametros de entrada*/
p_DESCRICAO IN SEGMERCADO.DESCRICAO%TYPE)
IS										        /* entre IS e BEGIN declara as variaveis*/
BEGIN
	INSERT INTO SEGMERCADO(ID, DESCRICAO) VALUES (p_ID, UPPER(p_DESCRICAO));
	COMMIT;
END;

/* APAGAR PROCEDURE */
DROP PROCEDURE INCLUIR_SEGMERCADO2;



/* EXERCICIO */
SELECT pe.* FROM PRODUTO_EXERCICIO pe 

CREATE OR REPLACE PROCEDURE INCLUINDO_PRODUTO
(p_COD IN PRODUTO_EXERCICIO.COD%TYPE,
p_DESCRICAO IN PRODUTO_EXERCICIO.DESCRICAO%TYPE,
p_CATEGORIA IN PRODUTO_EXERCICIO.CATEGORIA%TYPE)
IS
BEGIN 
	INSERT INTO PRODUTO_EXERCICIO(COD, DESCRICAO , CATEGORIA) VALUES(p_COD, p_DESCRICAO, p_CATEGORIA);
	COMMIT;
END;

BEGIN
	INCLUINDO_PRODUTO('89254', 'Frescor da Montanha - Aroma Uva - 1 Litro', 'Águas');
END;

CREATE OR REPLACE PROCEDURE ALTERANDO_CATEGORIA_PRODUTO
(p_COD IN PRODUTO_EXERCICIO.COD%TYPE,
p_CATEGORIA IN PRODUTO_EXERCICIO.CATEGORIA%TYPE)
IS
BEGIN 
	UPDATE PRODUTO_EXERCICIO SET CATEGORIA = p_CATEGORIA WHERE COD = p_COD;
	COMMIT;
END;

BEGIN 
	ALTERANDO_CATEGORIA_PRODUTO('33854', 'Águas');
END;

CREATE OR REPLACE PROCEDURE EXCLUINDO_PRODUTO 
(p_COD PRODUTO_EXERCICIO.COD%TYPE)
IS 
BEGIN
	DELETE FROM PRODUTO_EXERCICIO WHERE COD = p_COD;
	COMMIT;
END;

BEGIN 
	EXCLUINDO_PRODUTO('33854');
END;
/* EXERCICIO */
