DECLARE 
   v_SEGMERCADO CLIENTE.SEGMERCADO_ID%type := 3;
     v_ID CLIENTE.ID%type :=2;
     v_NUMCLI INTEGER;
BEGIN
   SELECT COUNT(*) INTO v_NUMCLI FROM CLIENTE;
     WHILE v_ID <= v_NUMCLI LOOP
        ATUALIZAR_SEG_MERCADO (v_ID,v_SEGMERCADO);
            v_ID := v_ID + 1; 
     END LOOP;
END;


/* CURSOR */
DECLARE
	v_ID CLIENTE.ID%TYPE;
	v_RAZAO CLIENTE.RAZAO_SOCIAL%TYPE;
	CURSOR cur_CLIENTE IS SELECT ID, RAZAO_SOCIAL FROM CLIENTE;
BEGIN 
	OPEN cur_CLIENTE;
	LOOP
		FETCH cur_CLIENTE INTO v_ID, v_RAZAO;
	EXIT WHEN cur_CLIENTE%NOTFOUND;
		dbms_output.put_line('ID = ' || v_ID || ', RAZAO = ' || v_RAZAO);
	END LOOP;
END;

SELECT c.* FROM CLIENTE c;


/* Atualiza todos inclusive aqueles que não seguem a ordem dos ids */
DECLARE
    v_SEGMERCADO CLIENTE.SEGMERCADO_ID%type := 4;
    v_ID CLIENTE.ID%TYPE;
    CURSOR cur_CLIENTE IS SELECT ID FROM CLIENTE;
BEGIN
    OPEN cur_CLIENTE;
    LOOP
		FETCH cur_CLIENTE INTO v_ID;
	EXIT WHEN cur_CLIENTE%NOTFOUND;
		ATUALIZAR_SEG_MERCADO(v_ID, v_SEGMERCADO);
    END LOOP;
    CLOSE cur_CLIENTE;
END;