SELECT * FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS; /* Não permite linhas repitidas, somente as combinações diferentes */

SELECT SABOR, COUNT(*) FROM TABELA_DE_PRODUTOS GROUP BY SABOR; /* Agrupa por sabor e apresenta a quantidade de produto de cada sabor*/

SELECT DISTINCT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM; 

SELECT * FROM TABELA_DE_CLIENTES WHERE ROWNUM <= 4; /* ROWNUM = Numero de linhas */

SELECT * FROM TABELA_DE_CLIENTES WHERE ROWNUM <= 10 ORDER BY DATA_DE_NASCIMENTO;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM, PRECO_DE_LISTA; 

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM DESC, PRECO_DE_LISTA; 



SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE 'Morango/Limao';

SELECT * FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC;


SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES ORDER BY CIDADE, IDADE;

SELECT CIDADE, AVG(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE ORDER BY CIDADE;

SELECT CIDADE, AVG(IDADE), AVG(LIMITE_DE_CREDITO) FROM TABELA_DE_CLIENTES GROUP BY CIDADE ORDER BY CIDADE;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;


SELECT CODIGO_DO_PRODUTO, COUNT(QUANTIDADE) FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99 GROUP BY CODIGO_DO_PRODUTO;

SELECT COUNT(*) FROM ITENS_NOTAS_FISCAIS WHERE codigo_do_produto = '1101035' AND quantidade = 99;


/* HAVING é muito pouco usado porém muito importante */
/* Ele permite que eu aplique um filtro sobre o resultado da agregação */

SELECT * FROM TABELA_DE_CLIENTES;

/* HAVING entra no lugar do WHERE*/
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) FROM TABELA_DE_CLIENTES HAVING SUM(LIMITE_DE_CREDITO) >= 900000 GROUP BY ESTADO;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS "Maior preco", MIN(PRECO_DE_LISTA) AS "Menor preco" 
FROM TABELA_DE_PRODUTOS WHERE PRECO_DE_LISTA >= 10 GROUP BY EMBALAGEM HAVING MAX(PRECO_DE_LISTA) >= 20;

SELECT * FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035';

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) FROM ITENS_NOTAS_FISCAIS GROUP BY CODIGO_DO_PRODUTO ORDER BY SUM(QUANTIDADE) DESC;

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) FROM ITENS_NOTAS_FISCAIS HAVING SUM(QUANTIDADE) >= 21500 GROUP BY CODIGO_DO_PRODUTO ORDER BY SUM(QUANTIDADE) DESC;

/* Classificando campos */
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
	(CASE
		WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
		WHEN PRECO_DE_LISTA >= 7
		AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO'
	END) AS CLASSIFICACAO
FROM
	TABELA_DE_PRODUTOS
ORDER BY 
	CLASSIFICACAO;


SELECT
	NOME, 
	(CASE
		WHEN LIMITE_DE_CREDITO >= 150000 THEN 'Clientes grandes'
		WHEN LIMITE_DE_CREDITO < 150000
		AND LIMITE_DE_CREDITO >= 110000 THEN 'Clientes médios'
		WHEN LIMITE_DE_CREDITO < 110000 THEN 'Clientes pequenos'
	END) AS CLASSIFICACAO
FROM
	TABELA_DE_CLIENTES
ORDER BY CLASSIFICACAO DESC;

