SELECT * FROM TABELA_DE_CLIENTES;

SELECT CPF, NOME, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT CPF AS IDENTIFICADOR, NOME, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT CPF AS IDENTIFICADOR, NOME AS "NOME DO CLIENTE", BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT TDC.* AS FROM TABELA_DE_CLIENTES TDC;