SELECT * FROM TABELA_DE_VENDEDORES tdv 

SELECT * FROM NOTAS_FISCAIS nf 

SELECT nf.MATRICULA, COUNT(*) FROM NOTAS_FISCAIS nf GROUP BY MATRICULA 

SELECT NF.MATRICULA, TDV.NOME, COUNT(*) 
FROM NOTAS_FISCAIS NF 
INNER JOIN TABELA_DE_VENDEDORES TDV 
ON NF.MATRICULA = TDV.MATRICULA /* critério de junção */
GROUP BY NF.MATRICULA, TDV.NOME;